/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Business Network
 */
public class BILLING extends javax.swing.JFrame {

    /**
     * Creates new form BILLING
     */
    public BILLING() {
        initComponents();
        printtable();
        
        
    }
    
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablebill = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        test = new javax.swing.JLabel();
        QUITBTN = new javax.swing.JToggleButton();
        CHKBTN = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        InfoLabel = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jScrollPane5.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 222, 173));

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 1, 36)); // NOI18N
        jLabel2.setText("YOUR TOTAL BILL");

        jScrollPane2.setBackground(new java.awt.Color(186, 79, 84));

        tablebill.setBackground(new java.awt.Color(255, 222, 173));
        tablebill.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tablebill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Items", "Price"
            }
        ));
        tablebill.setGridColor(new java.awt.Color(255, 222, 173));
        tablebill.setSelectionBackground(new java.awt.Color(255, 222, 173));
        jScrollPane2.setViewportView(tablebill);

        QUITBTN.setBackground(new java.awt.Color(255, 235, 205));
        QUITBTN.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        QUITBTN.setText("Quit");
        QUITBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QUITBTNActionPerformed(evt);
            }
        });

        CHKBTN.setBackground(new java.awt.Color(255, 235, 205));
        CHKBTN.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        CHKBTN.setText("Checkout");
        CHKBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHKBTNActionPerformed(evt);
            }
        });

        InfoLabel.setBackground(new java.awt.Color(255, 222, 173));
        InfoLabel.setColumns(20);
        InfoLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        InfoLabel.setRows(5);
        jScrollPane4.setViewportView(InfoLabel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(test))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QUITBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(CHKBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QUITBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CHKBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(test)
                        .addGap(84, 84, 84))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public int getSum() throws FileNotFoundException, IOException{
        
//          int temp;
//        int sum = 0;
//       
//        for(int i = 0 ; i < tablebill.getRowCount() ; i++){
//            temp =  Integer.parseInt(jTable1.getValueAt(i , 2).toString());
//            sum  = sum +temp;
//            
//        }
//        
//        InfoLabel.setText("Total" + sum);
//        

String filepath = "Bill.txt";
FileReader file = new FileReader("Bill.txt");
BufferedReader bf = new BufferedReader(file);
String st = bf.readLine();
Scanner sc = new Scanner(file);
int sum = 0 ;
int temp ;
while((st=bf.readLine())!=null){
    
    StringTokenizer stn = new StringTokenizer(st);
    String rn = stn.nextToken();
    String name = stn.nextToken();
    
    sum = Integer.parseInt(stn.nextToken());
    
    
    
    
//    temp = Integer.parseInt(sc.next().replaceAll("\\D+" , ""));
//    System.out.println("s : " +temp);
//    sum = sum + temp;   
}
System.out.println("Total" + sum);
InfoLabel.setText("Total" + sum);
return sum;



    }

void printtable(){
    String filepath = "BILL.txt";
 File file = new File(filepath);
 
        try { 
            BufferedReader br = new BufferedReader(new FileReader(file));
       Scanner s = new Scanner(file);
   
       DefaultTableModel model = (DefaultTableModel)tablebill.getModel();
        
  
        Object[] tableLines = br.lines().toArray();
        
        for(int i = 0 ; i < tableLines.length ; i++){
            
            String line = tableLines[i].toString().trim();
            String[] dataRow = line.split("/");
            model.addRow(dataRow);
            
        }
      
        
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Food_Types.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Food_Types.class.getName()).log(Level.SEVERE, null, ex);
        }
        

}

    
    
    public void total(){
        
        int total = 0;
        String temp;
        DefaultTableModel model = (DefaultTableModel)tablebill.getModel();
        try{
            for(int i = 0;i < tablebill.getRowCount();i++){
                temp =  model.getValueAt(i,1).toString().replaceAll("\\D+" , "");
                total+=Integer.parseInt(temp);
            }
             System.out.println(total);
        }
       
        catch(Exception e){
                System.out.println(e);
                }
      
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
   LocalDateTime now = LocalDateTime.now();  
   System.out.println(dtf.format(now)); 
        InfoLabel.setText("Your total amount is : "+total+" Rs.\n\nOrder Placed at:  "+dtf.format(now)+".\nWill Reach in 40-50mins....\n\n"+"Thankyou For Ordering!");
        
        
        
    }
    
    
    
    private void QUITBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QUITBTNActionPerformed
        // TODO add your handling code here:

  FileWriter fwOb = null; 
        try {
            fwOb = new FileWriter("Bill.txt", false);
        } catch (IOException ex) {
            Logger.getLogger(BILLING.class.getName()).log(Level.SEVERE, null, ex);
        }
        PrintWriter pwOb = new PrintWriter(fwOb, false);
        pwOb.flush();
        pwOb.close();
        try {
            fwOb.close();
            
            
        
        } catch (IOException ex) {
            Logger.getLogger(BILLING.class.getName()).log(Level.SEVERE, null, ex);
        }
System.exit(0);
    }//GEN-LAST:event_QUITBTNActionPerformed

    private void CHKBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHKBTNActionPerformed
     
        
        total();
        
    }//GEN-LAST:event_CHKBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BILLING().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CHKBTN;
    private javax.swing.JTextArea InfoLabel;
    private javax.swing.JToggleButton QUITBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    public static javax.swing.JTable tablebill;
    public static javax.swing.JLabel test;
    // End of variables declaration//GEN-END:variables
}
