/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;

import java.io.FileOutputStream;
import java.io.PrintWriter;

/**
 *
 * @author Business Network
 */
public class CHINEASE extends javax.swing.JFrame {

    /**
     * Creates new form CHINEASE
     */
    public CHINEASE() {
        initComponents();
    }
  int sum;
    public CHINEASE(int i ){
                initComponents();
        this.sum = i;
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FRIEDCB = new javax.swing.JCheckBox();
        CHOWCB = new javax.swing.JCheckBox();
        WANCB = new javax.swing.JCheckBox();
        ACCEPTBTN = new javax.swing.JButton();
        BACKBTN = new javax.swing.JButton();
        MANCHCB = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 222, 173));
        jPanel1.setToolTipText("CHICKEN MANCHURIAN    490");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/noodle.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setText("CHOOSE YOUR  CHINESE:");

        FRIEDCB.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        FRIEDCB.setText("CHICKEN FRIED RICE         400rs.");
        FRIEDCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FRIEDCBActionPerformed(evt);
            }
        });

        CHOWCB.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        CHOWCB.setText(" CHICKEN CHOWMIN        500rs");
        CHOWCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHOWCBActionPerformed(evt);
            }
        });

        WANCB.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        WANCB.setText("CHICKEN SCHEZWAN        550rs.");
        WANCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WANCBActionPerformed(evt);
            }
        });

        ACCEPTBTN.setBackground(new java.awt.Color(255, 235, 205));
        ACCEPTBTN.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        ACCEPTBTN.setText("ACCEPT");
        ACCEPTBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACCEPTBTNActionPerformed(evt);
            }
        });

        BACKBTN.setBackground(new java.awt.Color(255, 235, 205));
        BACKBTN.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        BACKBTN.setText("BACK");
        BACKBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKBTNActionPerformed(evt);
            }
        });

        MANCHCB.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        MANCHCB.setText("CHICKEN MANCHURIAN    490rs");
        MANCHCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MANCHCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WANCB)
                            .addComponent(CHOWCB)
                            .addComponent(FRIEDCB)
                            .addComponent(MANCHCB))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ACCEPTBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BACKBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(FRIEDCB)
                .addGap(18, 18, 18)
                .addComponent(CHOWCB)
                .addGap(18, 18, 18)
                .addComponent(MANCHCB)
                .addGap(18, 18, 18)
                .addComponent(WANCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACCEPTBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BACKBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BACKBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKBTNActionPerformed
 this.dispose();
        Food_Types f1 = new Food_Types();
        f1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BACKBTNActionPerformed

    private void ACCEPTBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACCEPTBTNActionPerformed
        // TODO add your handling code here
                        PrintWriter pw = null;
        try {
            FileOutputStream file = new FileOutputStream("Bill.txt", true);
     pw = new PrintWriter(file);
    
            
        } catch (Exception e) {
            System.out.println("ERROR!");
        }
              if(FRIEDCB.isSelected()){
          pw.println("Chicken Fried Rice / 400rs");sum = sum + 400;
        }
        if(CHOWCB.isSelected()){
            
          pw.println("Chicken Chowmin / 500rs"); sum = sum + 500;
        }
        if(MANCHCB.isSelected()){
            
          pw.println("Chicken Manchurian / 460rs");sum = sum + 460;
        }
        if(WANCB.isSelected()){
           
            pw.println("Chicken Shezwan / 550rs");sum = sum + 550;
        }
        pw.close();
        this.setVisible(false);
        Food_Types f1 = new Food_Types();
f1.setVisible(true);
   
        
        
   
         
    }//GEN-LAST:event_ACCEPTBTNActionPerformed

    private void WANCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WANCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WANCBActionPerformed

    private void CHOWCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHOWCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHOWCBActionPerformed

    private void FRIEDCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FRIEDCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FRIEDCBActionPerformed

    private void MANCHCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MANCHCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MANCHCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHINEASE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHINEASE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHINEASE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHINEASE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHINEASE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACCEPTBTN;
    private javax.swing.JButton BACKBTN;
    private javax.swing.JCheckBox CHOWCB;
    private javax.swing.JCheckBox FRIEDCB;
    private javax.swing.JCheckBox MANCHCB;
    private javax.swing.JCheckBox WANCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
