/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Business Network
 */
public class DRINKS extends javax.swing.JFrame {

    /**
     * Creates new form DRINKS
     */
    public DRINKS() {
        initComponents();
    }
    
   int sum;
    public DRINKS(int i ){
                initComponents();
        this.sum = i;
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PEPSICB = new javax.swing.JCheckBox();
        UPCB = new javax.swing.JCheckBox();
        DEWCB = new javax.swing.JCheckBox();
        WATERCB = new javax.swing.JCheckBox();
        ACCEPTBTN = new javax.swing.JButton();
        BACKBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 222, 173));

        jLabel1.setBackground(new java.awt.Color(255, 222, 173));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/soft-drink.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setText("CHOOSE YOUR DRINKS:");

        PEPSICB.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        PEPSICB.setText("PEPSI                               60rs.");
        PEPSICB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PEPSICBActionPerformed(evt);
            }
        });

        UPCB.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        UPCB.setText("7UP                                 60rs");
        UPCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPCBActionPerformed(evt);
            }
        });

        DEWCB.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        DEWCB.setText("MOUNTAIN DEW             60rs.");
        DEWCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEWCBActionPerformed(evt);
            }
        });

        WATERCB.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        WATERCB.setText("WATER                            50rs.");
        WATERCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WATERCBActionPerformed(evt);
            }
        });

        ACCEPTBTN.setBackground(new java.awt.Color(255, 235, 205));
        ACCEPTBTN.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        ACCEPTBTN.setText("ACCEPT");
        ACCEPTBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACCEPTBTNActionPerformed(evt);
            }
        });

        BACKBTN.setBackground(new java.awt.Color(255, 235, 205));
        BACKBTN.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        BACKBTN.setText("BACK");
        BACKBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ACCEPTBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(BACKBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WATERCB)
                    .addComponent(DEWCB)
                    .addComponent(UPCB)
                    .addComponent(PEPSICB))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addComponent(PEPSICB)
                .addGap(18, 18, 18)
                .addComponent(UPCB)
                .addGap(18, 18, 18)
                .addComponent(DEWCB)
                .addGap(18, 18, 18)
                .addComponent(WATERCB)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BACKBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACCEPTBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PEPSICBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PEPSICBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PEPSICBActionPerformed

    private void UPCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UPCBActionPerformed

    private void DEWCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEWCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DEWCBActionPerformed

    private void WATERCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WATERCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WATERCBActionPerformed
    private void ACCEPTBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACCEPTBTNActionPerformed
        // TODO add your handling code here:
       
               PrintWriter pw = null;
        try {
            FileOutputStream file = new FileOutputStream("Bill.txt", true);
     pw = new PrintWriter(file);
    
            
        } catch (Exception e) {
            System.out.println("ERROR!");
        }
         
        if(PEPSICB.isSelected()){
          pw.println("Pepsi / 60rs");sum = sum + 60;
        }
        if(UPCB.isSelected()){
            
          pw.println("7UP / 60rs");sum= sum+60;
        }
        if(DEWCB.isSelected()){
            
          pw.println(" Dew / 60rs"); sum = sum + 60;
        }
        if(WATERCB.isSelected()){
           
            pw.println("Water / 50rs"); sum = sum + 50;
        }
        pw.close();
        this.setVisible(false);
        Food_Types f1 = new Food_Types();
f1.setVisible(true);
    }//GEN-LAST:event_ACCEPTBTNActionPerformed

    private void BACKBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKBTNActionPerformed
 this.dispose();
        Food_Types f1 = new Food_Types();
        f1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BACKBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DRINKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DRINKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DRINKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DRINKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DRINKS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACCEPTBTN;
    private javax.swing.JButton BACKBTN;
    private javax.swing.JCheckBox DEWCB;
    private javax.swing.JCheckBox PEPSICB;
    private javax.swing.JCheckBox UPCB;
    private javax.swing.JCheckBox WATERCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
