/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Business Network
 */
public class Food_Types2 extends javax.swing.JFrame {

    /**
     * Creates new form Food_Types2
     */
    public Food_Types2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Food_Types2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Food_Types2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Food_Types2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Food_Types2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Food_Types2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACCEPTBTN;
    private javax.swing.JButton ACCEPTBTN1;
    private javax.swing.JButton ACCEPTBTN10;
    private javax.swing.JButton ACCEPTBTN11;
    private javax.swing.JButton ACCEPTBTN12;
    private javax.swing.JButton ACCEPTBTN13;
    private javax.swing.JButton ACCEPTBTN14;
    private javax.swing.JButton ACCEPTBTN15;
    private javax.swing.JButton ACCEPTBTN16;
    private javax.swing.JButton ACCEPTBTN17;
    private javax.swing.JButton ACCEPTBTN18;
    private javax.swing.JButton ACCEPTBTN19;
    private javax.swing.JButton ACCEPTBTN2;
    private javax.swing.JButton ACCEPTBTN20;
    private javax.swing.JButton ACCEPTBTN21;
    private javax.swing.JButton ACCEPTBTN22;
    private javax.swing.JButton ACCEPTBTN23;
    private javax.swing.JButton ACCEPTBTN24;
    private javax.swing.JButton ACCEPTBTN25;
    private javax.swing.JButton ACCEPTBTN26;
    private javax.swing.JButton ACCEPTBTN27;
    private javax.swing.JButton ACCEPTBTN28;
    private javax.swing.JButton ACCEPTBTN29;
    private javax.swing.JButton ACCEPTBTN3;
    private javax.swing.JButton ACCEPTBTN30;
    private javax.swing.JButton ACCEPTBTN31;
    private javax.swing.JButton ACCEPTBTN32;
    private javax.swing.JButton ACCEPTBTN33;
    private javax.swing.JButton ACCEPTBTN34;
    private javax.swing.JButton ACCEPTBTN35;
    private javax.swing.JButton ACCEPTBTN36;
    private javax.swing.JButton ACCEPTBTN37;
    private javax.swing.JButton ACCEPTBTN38;
    private javax.swing.JButton ACCEPTBTN4;
    private javax.swing.JButton ACCEPTBTN5;
    private javax.swing.JButton ACCEPTBTN6;
    private javax.swing.JButton ACCEPTBTN7;
    private javax.swing.JButton ACCEPTBTN8;
    private javax.swing.JButton ACCEPTBTN9;
    private javax.swing.JCheckBox AMERICANCB;
    private javax.swing.JCheckBox AMERICANCB1;
    private javax.swing.JCheckBox AMERICANCB10;
    private javax.swing.JCheckBox AMERICANCB11;
    private javax.swing.JCheckBox AMERICANCB12;
    private javax.swing.JCheckBox AMERICANCB13;
    private javax.swing.JCheckBox AMERICANCB14;
    private javax.swing.JCheckBox AMERICANCB15;
    private javax.swing.JCheckBox AMERICANCB16;
    private javax.swing.JCheckBox AMERICANCB17;
    private javax.swing.JCheckBox AMERICANCB18;
    private javax.swing.JCheckBox AMERICANCB19;
    private javax.swing.JCheckBox AMERICANCB2;
    private javax.swing.JCheckBox AMERICANCB20;
    private javax.swing.JCheckBox AMERICANCB21;
    private javax.swing.JCheckBox AMERICANCB22;
    private javax.swing.JCheckBox AMERICANCB23;
    private javax.swing.JCheckBox AMERICANCB24;
    private javax.swing.JCheckBox AMERICANCB25;
    private javax.swing.JCheckBox AMERICANCB26;
    private javax.swing.JCheckBox AMERICANCB27;
    private javax.swing.JCheckBox AMERICANCB28;
    private javax.swing.JCheckBox AMERICANCB29;
    private javax.swing.JCheckBox AMERICANCB3;
    private javax.swing.JCheckBox AMERICANCB30;
    private javax.swing.JCheckBox AMERICANCB31;
    private javax.swing.JCheckBox AMERICANCB32;
    private javax.swing.JCheckBox AMERICANCB33;
    private javax.swing.JCheckBox AMERICANCB34;
    private javax.swing.JCheckBox AMERICANCB35;
    private javax.swing.JCheckBox AMERICANCB36;
    private javax.swing.JCheckBox AMERICANCB37;
    private javax.swing.JCheckBox AMERICANCB38;
    private javax.swing.JCheckBox AMERICANCB4;
    private javax.swing.JCheckBox AMERICANCB5;
    private javax.swing.JCheckBox AMERICANCB6;
    private javax.swing.JCheckBox AMERICANCB7;
    private javax.swing.JCheckBox AMERICANCB8;
    private javax.swing.JCheckBox AMERICANCB9;
    private javax.swing.JButton BACKBTN;
    private javax.swing.JButton BACKBTN1;
    private javax.swing.JButton BACKBTN10;
    private javax.swing.JButton BACKBTN11;
    private javax.swing.JButton BACKBTN12;
    private javax.swing.JButton BACKBTN13;
    private javax.swing.JButton BACKBTN14;
    private javax.swing.JButton BACKBTN15;
    private javax.swing.JButton BACKBTN16;
    private javax.swing.JButton BACKBTN17;
    private javax.swing.JButton BACKBTN18;
    private javax.swing.JButton BACKBTN19;
    private javax.swing.JButton BACKBTN20;
    private javax.swing.JButton BACKBTN21;
    private javax.swing.JButton BACKBTN22;
    private javax.swing.JButton BACKBTN23;
    private javax.swing.JButton BACKBTN24;
    private javax.swing.JButton BACKBTN25;
    private javax.swing.JButton BACKBTN26;
    private javax.swing.JButton BACKBTN27;
    private javax.swing.JButton BACKBTN28;
    private javax.swing.JButton BACKBTN29;
    private javax.swing.JButton BACKBTN3;
    private javax.swing.JButton BACKBTN30;
    private javax.swing.JButton BACKBTN31;
    private javax.swing.JButton BACKBTN32;
    private javax.swing.JButton BACKBTN33;
    private javax.swing.JButton BACKBTN34;
    private javax.swing.JButton BACKBTN35;
    private javax.swing.JButton BACKBTN36;
    private javax.swing.JButton BACKBTN37;
    private javax.swing.JButton BACKBTN38;
    private javax.swing.JButton BACKBTN39;
    private javax.swing.JButton BACKBTN4;
    private javax.swing.JButton BACKBTN40;
    private javax.swing.JButton BACKBTN41;
    private javax.swing.JButton BACKBTN5;
    private javax.swing.JButton BACKBTN6;
    private javax.swing.JButton BACKBTN7;
    private javax.swing.JButton BACKBTN8;
    private javax.swing.JButton BACKBTN9;
    private javax.swing.JLabel Burgerlabel;
    private javax.swing.JLabel Burgerlabel1;
    private javax.swing.JLabel Chineaselable;
    private javax.swing.JLabel Chineaselable1;
    private javax.swing.JLabel Drinklable;
    private javax.swing.JLabel Drinklable1;
    private javax.swing.JCheckBox MASHROOMCB;
    private javax.swing.JCheckBox MASHROOMCB1;
    private javax.swing.JCheckBox MASHROOMCB10;
    private javax.swing.JCheckBox MASHROOMCB11;
    private javax.swing.JCheckBox MASHROOMCB12;
    private javax.swing.JCheckBox MASHROOMCB13;
    private javax.swing.JCheckBox MASHROOMCB14;
    private javax.swing.JCheckBox MASHROOMCB15;
    private javax.swing.JCheckBox MASHROOMCB16;
    private javax.swing.JCheckBox MASHROOMCB17;
    private javax.swing.JCheckBox MASHROOMCB18;
    private javax.swing.JCheckBox MASHROOMCB19;
    private javax.swing.JCheckBox MASHROOMCB2;
    private javax.swing.JCheckBox MASHROOMCB20;
    private javax.swing.JCheckBox MASHROOMCB21;
    private javax.swing.JCheckBox MASHROOMCB22;
    private javax.swing.JCheckBox MASHROOMCB23;
    private javax.swing.JCheckBox MASHROOMCB24;
    private javax.swing.JCheckBox MASHROOMCB25;
    private javax.swing.JCheckBox MASHROOMCB26;
    private javax.swing.JCheckBox MASHROOMCB27;
    private javax.swing.JCheckBox MASHROOMCB28;
    private javax.swing.JCheckBox MASHROOMCB29;
    private javax.swing.JCheckBox MASHROOMCB3;
    private javax.swing.JCheckBox MASHROOMCB30;
    private javax.swing.JCheckBox MASHROOMCB31;
    private javax.swing.JCheckBox MASHROOMCB32;
    private javax.swing.JCheckBox MASHROOMCB33;
    private javax.swing.JCheckBox MASHROOMCB34;
    private javax.swing.JCheckBox MASHROOMCB35;
    private javax.swing.JCheckBox MASHROOMCB36;
    private javax.swing.JCheckBox MASHROOMCB37;
    private javax.swing.JCheckBox MASHROOMCB38;
    private javax.swing.JCheckBox MASHROOMCB4;
    private javax.swing.JCheckBox MASHROOMCB5;
    private javax.swing.JCheckBox MASHROOMCB6;
    private javax.swing.JCheckBox MASHROOMCB7;
    private javax.swing.JCheckBox MASHROOMCB8;
    private javax.swing.JCheckBox MASHROOMCB9;
    private javax.swing.JLabel Pizzalable;
    private javax.swing.JLabel Pizzalable1;
    private javax.swing.JCheckBox SPECIALCB;
    private javax.swing.JCheckBox SPECIALCB1;
    private javax.swing.JCheckBox SPECIALCB10;
    private javax.swing.JCheckBox SPECIALCB11;
    private javax.swing.JCheckBox SPECIALCB12;
    private javax.swing.JCheckBox SPECIALCB13;
    private javax.swing.JCheckBox SPECIALCB14;
    private javax.swing.JCheckBox SPECIALCB15;
    private javax.swing.JCheckBox SPECIALCB16;
    private javax.swing.JCheckBox SPECIALCB17;
    private javax.swing.JCheckBox SPECIALCB18;
    private javax.swing.JCheckBox SPECIALCB19;
    private javax.swing.JCheckBox SPECIALCB2;
    private javax.swing.JCheckBox SPECIALCB20;
    private javax.swing.JCheckBox SPECIALCB21;
    private javax.swing.JCheckBox SPECIALCB22;
    private javax.swing.JCheckBox SPECIALCB23;
    private javax.swing.JCheckBox SPECIALCB24;
    private javax.swing.JCheckBox SPECIALCB25;
    private javax.swing.JCheckBox SPECIALCB26;
    private javax.swing.JCheckBox SPECIALCB27;
    private javax.swing.JCheckBox SPECIALCB28;
    private javax.swing.JCheckBox SPECIALCB29;
    private javax.swing.JCheckBox SPECIALCB3;
    private javax.swing.JCheckBox SPECIALCB30;
    private javax.swing.JCheckBox SPECIALCB31;
    private javax.swing.JCheckBox SPECIALCB32;
    private javax.swing.JCheckBox SPECIALCB33;
    private javax.swing.JCheckBox SPECIALCB34;
    private javax.swing.JCheckBox SPECIALCB35;
    private javax.swing.JCheckBox SPECIALCB36;
    private javax.swing.JCheckBox SPECIALCB37;
    private javax.swing.JCheckBox SPECIALCB38;
    private javax.swing.JCheckBox SPECIALCB4;
    private javax.swing.JCheckBox SPECIALCB5;
    private javax.swing.JCheckBox SPECIALCB6;
    private javax.swing.JCheckBox SPECIALCB7;
    private javax.swing.JCheckBox SPECIALCB8;
    private javax.swing.JCheckBox SPECIALCB9;
    private javax.swing.JCheckBox STEAKCB;
    private javax.swing.JCheckBox STEAKCB1;
    private javax.swing.JCheckBox STEAKCB10;
    private javax.swing.JCheckBox STEAKCB11;
    private javax.swing.JCheckBox STEAKCB12;
    private javax.swing.JCheckBox STEAKCB13;
    private javax.swing.JCheckBox STEAKCB14;
    private javax.swing.JCheckBox STEAKCB15;
    private javax.swing.JCheckBox STEAKCB16;
    private javax.swing.JCheckBox STEAKCB17;
    private javax.swing.JCheckBox STEAKCB18;
    private javax.swing.JCheckBox STEAKCB19;
    private javax.swing.JCheckBox STEAKCB2;
    private javax.swing.JCheckBox STEAKCB20;
    private javax.swing.JCheckBox STEAKCB21;
    private javax.swing.JCheckBox STEAKCB22;
    private javax.swing.JCheckBox STEAKCB23;
    private javax.swing.JCheckBox STEAKCB24;
    private javax.swing.JCheckBox STEAKCB25;
    private javax.swing.JCheckBox STEAKCB26;
    private javax.swing.JCheckBox STEAKCB27;
    private javax.swing.JCheckBox STEAKCB28;
    private javax.swing.JCheckBox STEAKCB29;
    private javax.swing.JCheckBox STEAKCB3;
    private javax.swing.JCheckBox STEAKCB30;
    private javax.swing.JCheckBox STEAKCB31;
    private javax.swing.JCheckBox STEAKCB32;
    private javax.swing.JCheckBox STEAKCB33;
    private javax.swing.JCheckBox STEAKCB34;
    private javax.swing.JCheckBox STEAKCB35;
    private javax.swing.JCheckBox STEAKCB36;
    private javax.swing.JCheckBox STEAKCB37;
    private javax.swing.JCheckBox STEAKCB38;
    private javax.swing.JCheckBox STEAKCB4;
    private javax.swing.JCheckBox STEAKCB5;
    private javax.swing.JCheckBox STEAKCB6;
    private javax.swing.JCheckBox STEAKCB7;
    private javax.swing.JCheckBox STEAKCB8;
    private javax.swing.JCheckBox STEAKCB9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
