/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;

import java.io.FileOutputStream;
import java.io.PrintWriter;

/**
 *
 * @author Business Network
 */
public class PIZZAS extends javax.swing.JFrame {

    /**
     * Creates new form PIZZAS
     */
    public PIZZAS() {
        initComponents();
    }
  int sum;
    public PIZZAS(int i ){
                initComponents();
        this.sum = i;
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FAJITACB = new javax.swing.JCheckBox();
        VEGGIECB = new javax.swing.JCheckBox();
        CREAMYCB = new javax.swing.JCheckBox();
        SPECIALPIZZACB = new javax.swing.JCheckBox();
        ACCEPTBTN = new javax.swing.JButton();
        BACKBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 222, 173));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/pizza.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setText("CHOOSE YOUR PIZZAS:");

        FAJITACB.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        FAJITACB.setText("FAJITA PIZZA                      760rs");
        FAJITACB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAJITACBActionPerformed(evt);
            }
        });

        VEGGIECB.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        VEGGIECB.setText("ALL VEGGIES                       550rs");
        VEGGIECB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEGGIECBActionPerformed(evt);
            }
        });

        CREAMYCB.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        CREAMYCB.setText("CREAMY CHEESE PIZZA      770rs");
        CREAMYCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREAMYCBActionPerformed(evt);
            }
        });

        SPECIALPIZZACB.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        SPECIALPIZZACB.setText("THE FOOD SPECIAL PIZZA  950rs.");
        SPECIALPIZZACB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPECIALPIZZACBActionPerformed(evt);
            }
        });

        ACCEPTBTN.setBackground(new java.awt.Color(255, 235, 205));
        ACCEPTBTN.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        ACCEPTBTN.setText("ACCEPT");
        ACCEPTBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACCEPTBTNActionPerformed(evt);
            }
        });

        BACKBTN.setBackground(new java.awt.Color(255, 235, 205));
        BACKBTN.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        BACKBTN.setText("BACK");
        BACKBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPECIALPIZZACB)
                    .addComponent(CREAMYCB)
                    .addComponent(VEGGIECB)
                    .addComponent(FAJITACB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(ACCEPTBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BACKBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(FAJITACB)
                .addGap(18, 18, 18)
                .addComponent(VEGGIECB)
                .addGap(18, 18, 18)
                .addComponent(CREAMYCB)
                .addGap(18, 18, 18)
                .addComponent(SPECIALPIZZACB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACCEPTBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BACKBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FAJITACBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAJITACBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FAJITACBActionPerformed

    private void VEGGIECBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEGGIECBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VEGGIECBActionPerformed

    private void CREAMYCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREAMYCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CREAMYCBActionPerformed

    private void SPECIALPIZZACBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPECIALPIZZACBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPECIALPIZZACBActionPerformed

    private void ACCEPTBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACCEPTBTNActionPerformed
        // TODO add your handling code here:
                      PrintWriter pw = null;
        try {
            FileOutputStream file = new FileOutputStream("Bill.txt", true);
     pw = new PrintWriter(file);
    
            
        } catch (Exception e) {
            System.out.println("ERROR!");
        }
              if(CREAMYCB.isSelected()){
          pw.println("Creamy Pizza / 400rs"); sum = sum + 400;
        }
        if(FAJITACB.isSelected()){
            
          pw.println("Fajita Pizza / 760rs");sum = sum + 760;
        }
        if(SPECIALPIZZACB.isSelected()){
            
          pw.println("The Food Special Pizza / 950rs");sum = sum + 950;
        }
        if(VEGGIECB.isSelected()){
           
            pw.println("All Veggies / 550rs");sum = sum + 550;
        }
        pw.close();
        this.setVisible(false);
        Food_Types f1 = new Food_Types();
f1.setVisible(true);
   
        
        
        
    }//GEN-LAST:event_ACCEPTBTNActionPerformed

    private void BACKBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKBTNActionPerformed
 this.dispose();
        Food_Types f1 = new Food_Types();
        f1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BACKBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PIZZAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PIZZAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PIZZAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PIZZAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PIZZAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACCEPTBTN;
    private javax.swing.JButton BACKBTN;
    private javax.swing.JCheckBox CREAMYCB;
    private javax.swing.JCheckBox FAJITACB;
    private javax.swing.JCheckBox SPECIALPIZZACB;
    private javax.swing.JCheckBox VEGGIECB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
